spring.application.name=sga

# --- Base de datos H2 en memoria ---
spring.datasource.url=jdbc:h2:mem:sgadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Consola web de H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Servidor ---
server.port=8080